Allow re-indexing of blogs and update solarium version
uoe-dlam/wp-solr pull request #14
Opened 2022-01-28 11:10 UTC by richeduni

2022-01-28 15:56 UTC, Sephster requested changes

2022-01-28 15:56 UTC, Sephster commented on .gitignore
> +solr-8.0.0.tgz
I think some of these rules might be specific to you. We should only include common exclusions in the .gitignore file. Anything local to you should go into .git/info/exclude - please review and change accordingly. Cheers Richard

2022-01-28 15:56 UTC, Sephster commented on CHANGELOG.md
> +- Fix re-indexing of blogs and update solarium version (PR #14)
Can we add more information here? It would be good to say that re-indexing has been moved to the CLI to avoid PHP timeouts. The Changelog is for end users so we should provide a decent amount of info here. Thanks Richard

2022-01-28 15:56 UTC, Sephster commented on admin/partials/ed-solr-admin-display.php
> +		To re-index all post, you should do the following:<br><br>
Would this look better in `<p>` tags. The double break might not be necessary here if that change is made

2022-01-28 15:56 UTC, Sephster commented on admin/partials/ed-solr-admin-display.php
> +        Prerequisites:<br><br>
I would move the pre-requisites to the top of the instructions

2022-01-28 15:56 UTC, Sephster commented on composer.json
> +        "solarium/solarium": "~6.0",
I think we should be using `^` here instead of `~`

2022-01-28 15:56 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +			$buffer->setBufferSize( 100 );
Magic number here. Would be good to convert to a constant with a logical name. Cheers Richard

2022-01-28 15:56 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +			$blogs = get_sites( 'number', '200000' );
Could convert number to constant here

2022-01-28 15:56 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				$posts = get_posts( - 1 );
Worth converting number to a constant

2022-01-28 15:56 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +			$message = '<p>The background indexing process has finished.</p><p>Status message: ' . ( $status === 0 ? 'All good (0)' : 'Something was not right  (' . $status . ')' ) . '<p><p>Thank you.</p>';
The _(0)_ in the message here might be confusing. It could be misinterpreted as no posts indexed. For the error message is the status text or a number? If it is a number, can we update the message to indicate it is a status message (perhaps even with a link so we can find out what this means). Cheers Richard

2022-01-28 15:56 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email sent.' );
I don't think we should be error logging a successful message.

2022-01-28 15:56 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email NOT sent' );
Any context we are able to add to this to make it more useful for debugging?

2022-01-28 15:56 UTC, Sephster commented on bin/ed-solr-index-blogs.sh
> +#!/usr/bin/env bash
do we need this file still?

2022-01-31 09:21 UTC, richeduni commented on admin/partials/ed-solr-admin-display.php
> +		To re-index all post, you should do the following:<br><br>
Done

2022-01-31 09:22 UTC, richeduni commented on admin/partials/ed-solr-admin-display.php
> +        Prerequisites:<br><br>
Done

2022-01-31 09:22 UTC, richeduni commented on composer.json
> +        "solarium/solarium": "~6.0",
Done

2022-01-31 09:22 UTC, richeduni commented on includes/class-ed-solr-index-blogs-cli.php
> +				$posts = get_posts( - 1 );
Done

2022-01-31 09:22 UTC, richeduni commented on includes/class-ed-solr-index-blogs-cli.php
> +			$message = '<p>The background indexing process has finished.</p><p>Status message: ' . ( $status === 0 ? 'All good (0)' : 'Something was not right  (' . $status . ')' ) . '<p><p>Thank you.</p>';
Done

2022-01-31 09:23 UTC, richeduni commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email sent.' );
Done

2022-01-31 09:23 UTC, richeduni commented on bin/ed-solr-index-blogs.sh
> +#!/usr/bin/env bash
No. Removed.

2022-01-31 09:31 UTC, richeduni commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email NOT sent' );
Done

2022-01-31 14:15 UTC, Sephster commented on .gitignore
> +solr-8.0.0.tgz
@richeduni this comment has been missed. Could you take another look please?

2022-01-31 14:16 UTC, Sephster commented on CHANGELOG.md
> +- Fix re-indexing of blogs and update solarium version (PR #14)
Done.

2022-01-31 14:18 UTC, richeduni commented on .gitignore
> +solr-8.0.0.tgz
I removed.idea. But solr-8.0.0 folders are created when you run the install solr bash script, so thought it made sense to keep them in here. Though happy to take out if you want.

2022-01-31 14:18 UTC, Sephster commented on admin/partials/ed-solr-admin-display.php
> +		To re-index all post, you should do the following:<br><br>
Thanks

2022-01-31 14:19 UTC, Sephster commented on admin/partials/ed-solr-admin-display.php
> +        Prerequisites:<br><br>
Cheers Richard

2022-01-31 14:19 UTC, Sephster commented on composer.json
> +        "solarium/solarium": "~6.0",
looks good. Thank you

2022-01-31 14:20 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				$posts = get_posts( - 1 );
Looks good. Thank you

2022-01-31 14:21 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +			$message = '<p>The background indexing process has finished.</p><p>Status message: ' . ( $status === 0 ? 'All good (0)' : 'Something was not right  (' . $status . ')' ) . '<p><p>Thank you.</p>';
Thanks Richard

2022-01-31 14:23 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email sent.' );
Thanks Richard.

2022-01-31 14:27 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email NOT sent' );
I'm not sure the fix is right here. The `$status` variable has been added to the error message but this is noting what went wrong with indexing, not with sending an email via wp_mail. Could  you take another look please @richeduni? Thank you

2022-01-31 14:28 UTC, Sephster commented on bin/ed-solr-index-blogs.sh
> +#!/usr/bin/env bash
Thanks Richard. Marking as resolved.

2022-01-31 14:35 UTC, Sephster commented on .gitignore
> +solr-8.0.0.tgz
Sorry, I saw you had just now. Marking as resolved. Thanks Richard.

2022-01-31 14:59 UTC, richeduni commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email sent.' );
Re-updated.

2022-01-31 17:01 UTC, Sephster commented on includes/class-ed-solr-index-blogs-cli.php
> +				error_log( 'Background process indexing end - email NOT sent' );
Looks good. Thanks Richard!

2022-01-31 17:01 UTC, Sephster approved these changes

2022-01-31 17:01 UTC, merged